<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        body {
            background-color: #f4f4f4;
        }
        .form-wrapper {
            margin: auto;
            width: 400px;
            padding: 10px;
            border-radius: 10px;
            background: #f4f4f4;
            box-shadow: 0px 3px 0px 0px #d4d4d4;
            border: 1px solid #d4d4d4;
            margin: auto;
            margin-top: 100px;
        }
        .header {
            margin: 20px 0;
            font-size: 24px;
            text-align: center;
            font-weight: bold;
        }
        .input-label {
            margin: 15px 0;
            font-size: 19px;
            text-align: center;
        }
        .button {
            flex: 1;
            margin: 20px 0;
            border-radius: 3px;
            padding: 3px 7px;
            text-decoration: none;
            color: #fff;
            background-color: #2ecc71;
            box-shadow: 0px 3px 0px 0px #15B358;
            font-size: 19px;
            text-align: center;
            cursor: pointer;
        }
        input {
            width: 98%;
            height: 25px;
            margin: 0;
            margin-bottom: 10px;
        }
        .error {
            text-align: center;
            margin-top: 10px;
            height: 20px;
            color: red;
        }
        .error.success {
            color: green;
        }
    </style>
    <script src="/assets/js/send-password-reset.js"></script>
</head>
<body>
<div class="form-wrapper">
    <div class="header">Изпратете email за възстановяване на парола</div>
    <div class="input-label">Email:</div>
    <input id="email" type="text" name="email">
    <div id="error" class="error"></div>
    <div class="button" onclick="onSend()">Изпрати email</div>
</div>
</body>
</html>
